# fly.toml app configuration file generated for reminderai-bot-telegram on 2025-05-30T03:40:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reminderai-bot-telegram'
primary_region = 'scl'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # <-- mantiene el bot corriendo siempre
  auto_start_machines = true
  min_machines_running = 1  # <-- fuerza solo una máquina activa
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
