app = 'reminderia-telegram-bot'
primary_region = 'scl'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # <-- mantiene el bot corriendo siempre
  auto_start_machines = true
  min_machines_running = 1  # <-- fuerza solo una máquina activa
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
